# Generated by Django 3.2.20 on 2023-07-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rssreader', '0009_rssfeed_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accept', 'Accept'), ('decline', 'Decline')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feed_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rssreader.feedentry')),
            ],
        ),
    ]
