# Generated by Django 3.2.20 on 2023-07-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('accept', 'Accept'), ('decline', 'Decline'), ('recycle', 'Recycle')], max_length=10),
        ),
    ]
