# Generated by Django 3.2.20 on 2023-07-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rssreader', '0009_rssfeed_description'),
        ('bidparser', '0003_rename_bid_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
