# Generated by Django 3.2.20 on 2023-07-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidparser', '0004_rename_jobs_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bid_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bidparser.job')),
            ],
        ),
    ]
