# Generated by Django 3.2.20 on 2023-07-20 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rssreader', '0009_rssfeed_description'),
        ('bidparser', '0005_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_header', models.TextField(default='')),
                ('prompt_body', models.TextField(default='')),
                ('prompt_footer', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prompt_feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rssreader.rssfeed')),
            ],
        ),
    ]
