# Generated by Django 3.2.20 on 2023-07-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidparser', '0006_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
