# Generated by Django 3.2.20 on 2023-07-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidparser', '0007_prompt_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
