# Generated by Django 3.2.20 on 2023-07-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidparser', '0008_prompt_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='prompt_feed',
            new_name='rss_feed',
        ),
    ]
