# Generated by Django 3.2.20 on 2023-07-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidparser', '0009_rename_prompt_feed_prompt_rss_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='iterations',
            field=models.IntegerField(default=1),
        ),
    ]
