# Generated by Django 3.2.20 on 2023-07-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssreader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedentry',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
