# Generated by Django 3.2.20 on 2023-07-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssreader', '0002_alter_feedentry_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedentry',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedentry',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedentry',
            name='job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedentry',
            name='pay_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedentry',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedentry',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
