# Generated by Django 3.2.20 on 2023-07-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssreader', '0004_auto_20230716_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
