# Generated by Django 3.2.20 on 2023-07-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rssreader', '0005_rssfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedentry',
            name='feed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rssreader.rssfeed'),
            preserve_default=False,
        ),
    ]
