# Generated by Django 3.2.20 on 2023-07-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssreader', '0006_feedentry_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
