# Generated by Django 3.2.20 on 2023-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssreader', '0007_alter_rssfeed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
