# Generated by Django 3.2.20 on 2023-07-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssreader', '0008_rssfeed_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
