# Generated by Django 3.2.20 on 2023-07-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssreader', '0009_rssfeed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedentry',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
